services:
- name: script-runner
  ports:
  - port: 8000
    http: true
  regions: [iad]
  scalings:
    min: 1
    max: 1
  health_checks:
    http:
      path: /
      port: 8000
      interval: 10s
      timeout: 5s
      healthy_threshold: 1
      unhealthy_threshold: 3
